language: node_js
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '5'
node_js:
- '4'
branches:
  except:
  - development-build
services:
- couchdb
env:
  global:
  - NODE_ENV=test
  - DEBUG_LEVEL=0
  - NAME=emails
  - TOKEN=apptoken
  - CXX=g++-4.8
  - secure: J2X6gwPCp2dwsHWmc0IzXYcJYkpSBDwkm3S3DmtveK5YcZp7DMiYwOvQJuyPYFIyQ4hl6WCM6IHePnhmY0Kdvha6+PCj4mXR/wVtVR+gAPvUK5KY8gu8XdhEPX65CutiSjP6PpOKeTyaT8YuehJaCNRo823V5z48Chn1ghnQGns=
  - secure: kVP5RYMRJg/GeMSYTV8rDUCGRskUcuiFj8UizF0xQ13P9+GQQqugnwK5vE/AcvC+kD5PRK+wBqFFAco9emyrFpg8PZnRoP4hyDY/lX8a6T5/1jbUwYTY6IXsFSSpFb5y2MbBEHscK5AF9redX73sm2SninD0RYLqAsY/Agdyj0s=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - gcc-4.8
    - g++-4.8
    - python3.5
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
- travis_retry npm install npm@latest-2 -g
- travis_retry npm install forever coffee-script -g
- travis_retry git clone git://github.com/cozy/cozy-data-system.git
- cd cozy-data-system
- travis_retry npm install
- env NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
- sleep 5
- coffee commands.coffee test-install emails
- cd ..
- mkdir log
- travis_retry npm install
script:
- npm run build
- npm run fixtures
- npm run test
- npm run lint:server
after_failure:
- cat cozy-data-system/forever-ds.log
- cat cozy-data-system/log/test.log
after_success:
- test $TRAVIS_BRANCH = "development" && npm run deploy
