language: node_js
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '5'
node_js:
- '4'
services:
- couchdb
env:
  global:
  - NODE_ENV=test
  - DEBUG_LEVEL=0
  - NAME=emails
  - TOKEN=apptoken
  - CXX=g++-4.8
  - secure: FVtPCjIQ5GdH4bANNbfZnkFKCPnakGJGFrhngBM/RpBGAs8SAb9C5AmniToYaT/NMIt+nFms87E/mYjqoFFjcrawqWPkaPwZqZqWaSX3mgNZz7cLiEo5+L59SDajqVcRACWFw9R4k4PtMnB4YW1j/cOp0HTUD8DIHU9gFpO/f80=
  - secure: H7oTliG3EspI3dqHWV2QqPA1+FXjmrHVh7rBLFVBln1jDHePF+73fNJK7EJ2cEhLyXmagXWSp7V888XaSlIAVcW+qeY0gCGzC1xPgAl2XbDdNimABEE6x3d4XJ3Mii3CjkY93p8RU05cM3n8/7CbnUSzZoz4spuYSfKfROAt0U8=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
- travis_retry npm install npm@latest-2 -g
- travis_retry npm install forever coffee-script -g
- travis_retry pip install --user transifex-client
- travis_retry git clone git://github.com/cozy/cozy-data-system.git
- git clone http://code.transifex.com/transifex-client
- cd transifex-client
- git checkout 0.12.1
- sudo python setup.py install
- cd $TRAVIS_BUILD_DIR
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
- cd cozy-data-system
- travis_retry npm install
- env NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
- sleep 5
- coffee commands.coffee test-install emails
- cd ..
- mkdir log
- travis_retry npm install
script:
- npm run build
- npm run fixtures
- npm run test
- npm run lint:server
after_failure:
- cat cozy-data-system/forever-ds.log
- cat cozy-data-system/log/test.log
after_success:
- test $TRAVIS_BRANCH = "development" && npm run deploy
